CREATE TABLE USUARIO (
     id BIGINT AUTO_INCREMENT PRIMARY KEY,
     dataDeCriacao TIMESTAMP NOT NULL,
     dataDaUltimaAlteracao TIMESTAMP NOT NULL,
     email VARCHAR(255) NOT NULL,
     endereco VARCHAR(255),
     login VARCHAR(100) NOT NULL,
     nome VARCHAR(100) NOT NULL,
     senha VARCHAR(255) NOT NULL
);