openapi: 3.0.3
info:
  title: Usuário API
  version: 1.0.0
  description: API para gerenciar usuários
servers:
  - url: http://localhost:8080/
    description: Servidor local
tags:
  - name: Usuários
    description: Operações relacionadas a usuários
paths:
  /usuarios:
    get:
      tags:
        - Usuários
      summary: Lista todos os usuários
      operationId: listarUsuarios
      responses:
        '200':
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Usuario'
    post:
      tags:
        - Usuários
      summary: Cria um novo usuário
      operationId: criarUsuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
      responses:
        '201':
          description: Usuário criado
components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        login:
          type: string
          maxLength: 50
          example: leonart
        email:
          type: string
          maxLength: 100
          example: leonart@email.com
        senha:
          type: string
          maxLength: 16
          example: senha123
        nome:
          type: string
          maxLength: 100
          example: Leonart Lima
        dataDaUltimaAlteracao:
          type: string
          maxLength: 20
          example: 2024-06-01T12:00:00
        dataDeCriacao:
          type: string
          maxLength: 20
          example: 2024-05-01T09:00:00
        endereco:
          type: string
          maxLength: 100
          example: Rua Exemplo, 123
      required:
        - login
        - email
        - senha
        - nome
        - dataDaUltimaAlteracao
        - dataDeCriacao
        - endereco